### ISSUE TITLE
no sound at the output

### ISSUE THREAD

**Issue by snilkov** [RowdyVoyeur/m8c-rpi4#7]
Hello, please;-)
I have an evo4 card connected to the pi and its name via aplay -l is EVO4, I rewrote the script m8c.sh according to your instructions and everything that had the name MC101 is now EVO4. then I checked the volume via alsamixer and it works. but when I start m8c everything works but I can't hear any sound on the output of the EVO4. I tried other cards and the same thing. can you please send me instructions what and where exactly to overwrite in the m8c.sh?

patch@patchbox:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: EVO4 [EVO4], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: M8 [M8], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

my settings ~/m8c-rpi4 /m8c.sh

#!/bin/bash

# Check if the Instrument with the Card Name "EVO4" is connected to the Raspberry Pi
# Use "aplay -l" to find the Card Name of any connected audio devices
if [ $(aplay -l | grep -c "EVO4") -eq 0 ]; then
  echo "EVO4 not detected, skipping connection."
else
  echo "EVO4 detected, connecting."

# Open audio interface between the Instrument Out and System In
# alsa_in options: -r is Sample Rate, -p is Period or Buffer Size, -n is Period, -q is Qua>
alsa_in -j "EVO4_in" -d hw:CARD=EVO4,DEV=0 -r 44100 -p 64 -n 4 &

# Open audio interface between System Out and Instrument In
# alsa_out options: -r is Sample Rate, -p is Period or Buffer Size, -n is Period, -q is Qu>
alsa_out -j "EVO4_out" -d hw:CARD=EVO4,DEV=0 -r 44100 -p 64 -n 4 &

sleep 2

# Connect audio of Instrument Out to System In (This allows to hear the additional Instrum>
jack_connect EVO4_in:capture_1 system:playback_1
jack_connect EVO4_in:capture_2 system:playback_2

# Connect audio of USB Card Microphone to EVO4 In (This allows to record audio onto the ad>
jack_connect system:capture_1 EVO4_out:playback_1
jack_connect system:capture_1 EVO4_out:playback_2

# Start MIDI To Command (Uncomment the line below to start midi-to-command on boot. More i>
# sudo python home/patch/midi-tools/midi-to-command/midi2command.py home/patch/midi-tools/>

fi

# Open audio interface between M8 Out and System In
# alsa_in options: -r is Sample Rate, -p is Period or Buffer Size, -n is Period, -q is Qua>
alsa_in -j "M8_in" -d hw:CARD=M8,DEV=0 -r 44100 -p 64 -n 4 &

# Open audio interface between System Out and M8 In
# alsa_out options: -r is Sample Rate, -p is Period or Buffer Size, -n is Period, -q is Qu>
alsa_out -j "M8_out" -d hw:CARD=M8,DEV=0 -r 44100 -p 64 -n 4 &

sleep 2

# Connect audio of M8 Out to System In (This allows to hear the M8)
jack_connect M8_in:capture_1 system:playback_1
jack_connect M8_in:capture_2 system:playback_2

# Connect audio of USB Card Microphone to M8 In (This allows to record audio onto the M8)
# There are 2 system:capture_1 because my USB Card has a mono ADC. Should be changed to ca>
jack_connect system:capture_1 M8_out:playback_1
jack_connect system:capture_1 M8_out:playback_2

# Start CC to Note (Uncomment the line below to start cc-to-note on boot. More info: githu>
# sudo python /home/patch/midi-tools/cc-to-note/main.py --config /home/patch/midi-tools/cc>

# Start Control Alsamixer (Uncomment the following line to start control-amixer on boot. M>
# sudo /bin/bash /home/patch/midi-tools/control-amixer/control-amixer.sh &

# Start M8C
pushd /home/patch/m8c-rpi4
./m8c
popd

# Clean up audio routing
killall -s SIGINT alsa_out alsa_in

# Shutdown after quitting M8C
sleep 2
sudo shutdown now

**Comment by RowdyVoyeur** [comment]
Hi. If that sound card is your main output, then you don't need to make changes to the m8c.sh. You would need to configure the soundcard in the Patchbox setup wizard.

**Comment by RowdyVoyeur** [comment]
I will close this because it's not an actual issue of the repo.
